### ISSUE TITLE
update image for meteor 1.6

### ISSUE THREAD

**Issue by aboire** [Treecom/alpine-meteor#4]
Meteor 1.6 uses the 8.8.1 version of node and npm 5.4.2

**Comment by abate** [comment]
same problem here. it fails with this error : 

```
=> Starting meteor app on port:80
/app/programs/server/boot.js:50
    const { pause } = require("./debug.js");
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/app/main.js:4:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```
that I'm pretty sure it's node related.
